name: example
description: Example project for auth_social_buttons

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auth_social_buttons:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true